# Generated by Django 5.2.5 on 2026-06-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('empresa', models.CharField(blank=True, default='', max_length=120)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=30)),
                ('notas', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ('nombre',),
            },
        ),
    ]
