# Generated by Django 5.2.5 on 2026-06-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_pedido_compra_pedidoitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ('empresa', 'nombre'), 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='area',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='blancos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='negros',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
