# Generated by Django 5.2.5 on 2026-06-06 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_cliente_options_cliente_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoitem',
            name='blancos',
        ),
        migrations.RemoveField(
            model_name='pedidoitem',
            name='negros',
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='gestion.pedidoitem')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
