# Generated by Django 5.2.5 on 2026-06-06 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BebesitaAPP', '0007_beneficiodiferencial_campanaespecial_and_more'),
        ('gestion', '0004_remove_pedidoitem_blancos_remove_pedidoitem_negros_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componente',
            name='nombre',
        ),
        migrations.AddField(
            model_name='componente',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='gestion_componentes', to='BebesitaAPP.producto'),
            preserve_default=False,
        ),
    ]
