# Generated by Django 5.2.5 on 2026-06-07 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BebesitaAPP', '0007_beneficiodiferencial_campanaespecial_and_more'),
        ('gestion', '0005_remove_componente_nombre_componente_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_unidad', models.PositiveIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gestion_costo', to='BebesitaAPP.producto')),
            ],
            options={
                'verbose_name': 'Costo por unidad',
                'verbose_name_plural': 'Costos por unidad',
            },
        ),
    ]
