# Generated by Django 5.2.16 on 2026-08-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BebesitaAPP', '0007_beneficiodiferencial_campanaespecial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cantidad_cajas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pedido',
            name='comentario_ocasion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pedido',
            name='costo_caja',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
