# Generated by Django 5.2.16 on 2026-09-12 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BebesitaAPP', '0008_pedido_cantidad_cajas_pedido_comentario_ocasion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidades_por_pack',
            field=models.PositiveIntegerField(default=1, help_text='Ej: 4 si la bolsita trae 4. Se usa solo para explicarlo.', verbose_name='Unidades por paquete'),
        ),
        migrations.AddField(
            model_name='producto',
            name='variante_de',
            field=models.ForeignKey(blank=True, help_text='Dejar vacío si es un producto normal.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='BebesitaAPP.producto', verbose_name='Es variante de'),
        ),
        migrations.AddField(
            model_name='producto',
            name='variante_nombre',
            field=models.CharField(blank=True, help_text='Lo que se lee en el selector. Ej: Chocolate blanco.', max_length=60, verbose_name='Nombre de la variante'),
        ),
    ]
