# Generated by Django 5.2.16 on 2026-09-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BebesitaAPP', '0009_producto_unidades_por_pack_producto_variante_de_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cobertura', 'Cobertura'), ('relleno', 'Relleno')], default='cobertura', max_length=20)),
                ('nombre', models.CharField(max_length=60)),
                ('color', models.CharField(default='#5b3a29', help_text='Hex del circulito que se ve en la tarjeta. Ej: #5b3a29 chocolate.', max_length=7, verbose_name='Color de la muestra')),
                ('recargo', models.IntegerField(default=0, help_text='Se suma al precio por unidad. 0 si cuesta lo mismo.')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Opción',
                'verbose_name_plural': 'Opciones (coberturas, rellenos)',
                'ordering': ('tipo', 'orden', 'nombre'),
            },
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='detalle',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='producto',
            name='opciones',
            field=models.ManyToManyField(blank=True, help_text='Coberturas y rellenos que el cliente puede elegir.', related_name='productos', to='BebesitaAPP.opcion'),
        ),
    ]
