# Generated by Django 5.2.16 on 2026-09-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BebesitaAPP', '0011_coberturas_iniciales'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClicEnlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=40)),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Clic en links',
                'verbose_name_plural': 'Clics en links (bio de Instagram)',
                'ordering': ('-creado',),
            },
        ),
    ]
