# Generated by Django 5.2.16 on 2026-09-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BebesitaAPP', '0012_clic_enlace'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=models.SlugField(blank=True, help_text='Se completa sola desde el nombre. Cambiarla rompe los enlaces ya compartidos.', max_length=120, verbose_name='Dirección web'),
        ),
    ]
