# Generated by Django 5.2.16 on 2026-09-15 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BebesitaAPP', '0014_rellenar_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='en_box',
            field=models.BooleanField(default=True, help_text='Desmarcar para productos que no caben en una caja (tortas).', verbose_name='Disponible en Arma tu box'),
        ),
        migrations.AddField(
            model_name='producto',
            name='minimo',
            field=models.PositiveIntegerField(default=0, help_text='0 = el mínimo general de la tienda (10). Una torta se vende desde 1.', verbose_name='Mínimo por pedido'),
        ),
        migrations.AddField(
            model_name='producto',
            name='pide_nota',
            field=models.BooleanField(default=False, help_text='En el carrito aparece un campo para describir cinta y decoración.', verbose_name='Pide nota al cliente'),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='tipo',
            field=models.CharField(choices=[('tamano', 'Tamaño'), ('cobertura', 'Cobertura'), ('relleno', 'Relleno')], default='cobertura', max_length=20),
        ),
        migrations.CreateModel(
            name='PrecioCombinacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_index=True, editable=False, max_length=60)),
                ('precio', models.IntegerField()),
                ('opciones', models.ManyToManyField(related_name='+', to='BebesitaAPP.opcion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_combinacion', to='BebesitaAPP.producto')),
            ],
            options={
                'verbose_name': 'Precio por combinación',
                'verbose_name_plural': 'Precios por combinación',
                'unique_together': {('producto', 'clave')},
            },
        ),
    ]
