# Generated by Django 6.0.5 on 2026-10-04 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BebesitaAPP', '0015_torta_minimo_nota_precios'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntafrecuente',
            name='producto',
            field=models.ForeignKey(blank=True, help_text='Vacio = sale en la portada. Con producto = sale en su ficha.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='BebesitaAPP.producto'),
        ),
    ]
