# Generated by Django 6.0.5 on 2026-10-04 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BebesitaAPP', '0016_pregunta_por_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Para ti. Ej: Dia del Profesor 2026.', max_length=80)),
                ('porcentaje', models.PositiveSmallIntegerField(help_text='Entre 1 y 60. Se aplica a todos los productos.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Descuento (%)')),
                ('desde', models.DateField(help_text='Primer dia en que se ve el descuento.')),
                ('hasta', models.DateField(help_text='Ultimo dia. Ese dia TODAVIA aplica.')),
                ('etiqueta', models.CharField(default='Oferta', help_text='Lo que dice el sello sobre el precio. Ej: Dia del Profesor.', max_length=60)),
                ('mensaje', models.CharField(blank=True, help_text='La franja de arriba. Ej: 10% en todo por el Dia del Profesor.', max_length=160)),
                ('activa', models.BooleanField(default=True, help_text='Desmarcar la apaga sin borrar nada ni perder las fechas.')),
            ],
            options={
                'verbose_name': 'Promocion',
                'verbose_name_plural': 'Promociones',
                'ordering': ('-desde',),
            },
        ),
    ]
